### ISSUE TITLE
Problems with User Data Script

### ISSUE THREAD

**Issue by donsamiro** [ventx/Terraform-AWS-OpenVPNServer#2]
Hi,
are you sure that your user data script is working? I am trying to execute it on an ec2 ubuntu 18.04 machine, but it is not working. 

First problem is that he is trying **sudo cp ca.crt server.crt server.key ta.key dh2048.pem /etc/openvpn** but server.cert and server.key are not created by the script (Step16)

The second problem is that he is not able to execute **sudo dpkg -i openvpn-as-*.deb
** (Step18)

I am getting the following output:

`(Reading database ... 59926 files and directories currently installed.)
Preparing to unpack openvpn-as-latest-ubuntu18.amd_64.deb ...
Upgrade detected (debian)...
Unpacking openvpn-as (2.7.5-932a08a3-Ubuntu18) over (2.7.5-932a08a3-Ubuntu18) ...
dpkg: dependency problems prevent configuration of openvpn-as:
 openvpn-as depends on openvpn-as-bundled-clients; however:
  Package openvpn-as-bundled-clients is not installed.

dpkg: error processing package openvpn-as (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 openvpn-as
`

Can you help me please?

**Comment by hajowieland** [comment]
Fixed UserData with #3 and use most-recent Ubuntu AMI

**Comment by 2kohm** [comment]
> Hi,
> are you sure that your user data script is working? I am trying to execute it on an ec2 ubuntu 18.04 machine, but it is not working.
> 
> First problem is that he is trying **sudo cp ca.crt server.crt server.key ta.key dh2048.pem /etc/openvpn** but server.cert and server.key are not created by the script (Step16)
> 
> The second problem is that he is not able to execute **sudo dpkg -i openvpn-as-*.deb
> ** (Step18)
> 
> I am getting the following output:
> 
> `(Reading database ... 59926 files and directories currently installed.)
> Preparing to unpack openvpn-as-latest-ubuntu18.amd_64.deb ...
> Upgrade detected (debian)...
> Unpacking openvpn-as (2.7.5-932a08a3-Ubuntu18) over (2.7.5-932a08a3-Ubuntu18) ...
> dpkg: dependency problems prevent configuration of openvpn-as:
> openvpn-as depends on openvpn-as-bundled-clients; however:
> Package openvpn-as-bundled-clients is not installed.
> 
> dpkg: error processing package openvpn-as (--install):
> dependency problems - leaving unconfigured
> Errors were encountered while processing:
> openvpn-as
> `
> 
> Can you help me please?

Hi donsamiro, thanks for your message!
@hajowieland fixed this issue, see ->[[fix] UserData, use most-recent Ubuntu AMI #3
]( https://github.com/ventx/Terraform-AWS-OpenVPNServer/pull/3)
