### ISSUE TITLE
Install certbot

### ISSUE THREAD

**Issue by donsamiro** [ventx/Terraform-AWS-OpenVPNServer#4]
Hello,

it seems to me that the install certbot code is wrong. I have replaced opevpn-as with openvpn and it worked for me.

**Comment by 2kohm** [comment]
Hello donsamiro,
what was the error message? we tested the stack and we had no issue with certobt 🤔

**Comment by donsamiro** [comment]
Hello 2kohm, 
thanks for your fast response. I had a message like "unable to find package openvpn-as".

**Comment by hajowieland** [comment]
@donsamiro Thanks for opening the issue.
Did you try the latest Master / 0.2.1 Version?  
There is an official OpenVPN apt repository which we now use in the UserData. 

```
apt-cache showpkg openvpn-as
Package: openvpn-as
Versions:
2.7.5-932a08a3-Ubuntu18 (/var/lib/apt/lists/as-repository.openvpn.net_as_debian_dists_bionic_main_binary-amd64_Packages) (/var/lib/dpkg/status)
 Description Language:
                 File: /var/lib/apt/lists/as-repository.openvpn.net_as_debian_dists_bionic_main_binary-amd64_Packages
                  MD5: 432364af46b12f148d7bd5611d8aaad3
```

**Comment by donsamiro** [comment]
@hajowieland yes I am actually trying to get this version running on my ec2 instances. I got some problems atm

**Comment by hajowieland** [comment]
Could you please send us the log from /var/log/cloud-init-output.log ?

**Comment by donsamiro** [comment]
@hajowieland I don't know why but it works now. Sorry for the confusion.
